# Conclusion

In this study, we examine the association between smoking exposure and health-related issues in the United States. To facilitate comparisons with previous studies mentioned in the Introduction, we use data gathered by the Centers for Disease Control and Prevention, from over 5000 people around the nation. We combined three datasets to study the association between ten health-related issues and both first-handed and second-handed smoking exposure. After exploring the combined dataset, we drop columns with too many missing values and redundant features. The remained dataset has two smoke-related features, or the independent features, and ten health-related issues, or the dependent features.

For first-handed smoking exposure, we explore the smoking frequency. For second-handed smoking exposure, we examine the number of smokers (except the questionnaire-respondent) in the respondent's household. For the ten health-related issues, we focus on diseases. Some selected diseases - include stroke, coronary heart disease, and cancer - were recognized as smoking-related issues in previous studies.

After applying multiple data visualization techniques, as shown in the Results section, we arrive at the following conclusions: both first-handed and second-handed smoking exposures has an influence on people's health condition in the United States, and the influences are similar for the two independent features. Smoking exposure has positive correlation with getting asthma, arthritis, COPD, emphysema, and ChB: the proportion of people who smoke daily or have more smokers in household is larger than that of people who do not smoke that often or have fewer smokers in household. On the other hand, the association between smoking exposure and coronary heart disease is not explicit: contradicts the previous studies.

A possible cause of the contradiction could be the lag of effect of smoking: if a person start to smoke and smoke daily, he or she may not have a health-related issue related to smoking. This pattern could be related to people's age. In future studies, we will further explore the impact of people's age and how many years they smoke. Despite this abnormality, our study conforms with the previous ones: that is, both first-handed and second-handed smoking exposures has an association with health-related issues in the United States.
